config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :pages do
      collection do
        post :update_positions
      end
    end
  end

  resources :pages, only: :show, path: 'p'
end

app/models/spree/page.rb
module Spree
  class Page < Spree::Base
    extend FriendlyId
    friendly_id :slug_candidates, use: [:slugged, :finders]

    belongs_to :page_section

    has_attached_file :image,
                      styles: { large: '600x600>' },
                      default_style: :large,
                      url: '/spree/pages/:id/:style/:basename.:extension',
                      path: ':rails_root/public/spree/pages/:id/:style/:basename.:extension',
                      convert_options: { all: '-strip -auto-orient -colorspace sRGB' }

    validates :title, presence: true
    validates_attachment :image, content_type: { content_type: /\Aimage\/.*\Z/ }

    scope :visible, -> { where(visible: true) }
    default_scope { order(:position) }

    def slug_candidates
      [:title]
    end

    def should_generate_new_friendly_id?
      title_changed?
    end
  end
end

app/models/spree/page_section.rb
class Spree::PageSection < Spree::Base
  has_many :pages, -> { visible }
end

app/controllers/spree/admin/pages_controller.rb
module Spree
  module Admin
    class PagesController < ResourceController
      def index
        @pages = Spree::Page.page(params[:page] || 1).per(50)
      end
    end
  end
end

app/controllers/spree/pages_controller.rb
module Spree
  class PagesController < StoreController
    def show
      @page = Spree::Page.visible.friendly.find(params[:id])
      @title = @page.title
    end
  end
end

app/views/spree/admin/pages/_form.html.erb
<div data-hook="admin_page_form_fields" class="row">
  <div class="col-md-6">
    <%= f.field_container :title do %>
      <%= f.label :title, t(:title, scope: 'activerecord.attributes.spree/page') %>
      <%= f.text_field :title, class: 'form-control' %>
      <%= error_message_on :page, :title %>
    <% end %>

    <%= f.field_container :body, class: ['form-group'] do %>
      <%= f.label :body, t(:body, scope: 'activerecord.attributes.spree/page') %>
      <%= f.text_area :body, class: 'form-control' %>
      <%= error_message_on :page, :body %>
    <% end %>

    <%= f.field_container :visible, class: ['form-group'] do %>
      <%= f.label :visible, t(:visible, scope: 'activerecord.attributes.spree/page') %>
      <%= f.check_box :visible, class: 'form-control' %>
      <%= error_message_on :page, :visible %>
    <% end %>

    <%= f.field_container :meta_keywords, class: ['form-group'] do %>
      <%= f.label :meta_keywords, t(:meta_keywords, scope: 'activerecord.attributes.spree/page') %>
      <%= f.text_field :meta_keywords, class: 'form-control' %>
      <%= error_message_on :page, :meta_keywords %>
    <% end %>

    <%= f.field_container :meta_description, class: ['form-group'] do %>
      <%= f.label :meta_description, t(:meta_description, scope: 'activerecord.attributes.spree/page') %>
      <%= f.text_field :meta_description, class: 'form-control' %>
      <%= error_message_on :page, :meta_description %>
    <% end %>

    <%= f.field_container :image, class: ['form-group'] do %>
      <%= f.label :image, t(:image, scope: 'activerecord.attributes.spree/page') %>
      <%= f.file_field :image, class: 'form-control' %>
      <%= error_message_on :page, :image %>
      <% if f.object.image_file_name %>
        <br><br>
        <%= image_tag f.object.image.url(:large) %>
      <% end %>
    <% end %>

    <%= f.field_container :page_section_id, class: ['form-group'] do %>
      <%= f.label :page_section_id, t(:page_section, scope: 'activerecord.attributes.spree/page') %>
      <%= f.collection_select :page_section_id, Spree::PageSection.all, :id, :name %>
      <%= error_message_on :page, :page_section_id %>
    <% end %>
  </div>
</div>

app/views/spree/admin/pages/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_page) %>
<% end %>

<div data-hook="admin_page_edit_form_header">
  <%= render 'spree/shared/error_messages', target: @page %>
</div>

<div data-hook="admin_page_edit_form">
  <%= form_for [:admin, @page] do |f| %>
    <div class="row">
      <div class="col-md-12">
        <%= render 'form', f: f %>
        <%= render 'spree/admin/shared/edit_resource_links' %>
      </div>
    </div>
  <% end %>
</div>

app/views/spree/admin/pages/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:listing_pages) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_page), new_object_url, class: 'btn-success', icon: 'add', id: 'admin_new_page_link' %>
<% end if can?(:create, Spree::Page) %>

<table class="table sortable" id="listing_pages" data-hook data-sortable-link="<%= update_positions_admin_pages_url %>">
  <thead>
    <tr data-hook="admin_pages_index_headers">
      <th class="no-border"></th>
      <th><%= t(:title, scope: 'activerecord.attributes.spree/page') %></th>
      <th data-hook="admin_pages_index_header_actions" class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @pages.each do |page| %>
      <tr id="<%= spree_dom_id page %>" data-hook="admin_pages_index_rows" class="<%= cycle('odd', 'even')%>">
        <td class="move-handle"><span class="icon icon-move handle"></span></td>
        <td><%= link_to page.title, edit_object_url(page) %></td>
        <td data-hook="admin_pages_index_row_actions" class="actions text-right">
          <%= link_to_edit page, no_text: true %>
          <%= link_to_with_icon("eye-open", Spree.t(:page_preview), page_path(page), class: "btn btn-primary btn-sm", no_text: true, target: "_blank") %>
          <%= link_to_delete page, no_text: true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @pages %>

app/views/spree/admin/pages/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_page) %>
<% end %>

<div data-hook="admin_page_new_form_header">
  <%= render 'spree/shared/error_messages', target: @page %>
</div>

<div data-hook="admin_page_new_form">
  <%= form_for [:admin, @page] do |f| %>
    <div class="row">
      <div class="col-md-12">
        <%= render 'form', f: f %>
        <%= render 'spree/admin/shared/edit_resource_links' %>
      </div>
    </div>
  <% end %>
</div>

app/views/spree/pages/show.html.erb
<h2><%= @page.title %></h2>

<p><%= raw @page.body %></p>